package com.sms.demo.mapper.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vipLevel
     *
     * @mbg.generated
     */
    private Integer viplevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phoneNum
     *
     * @mbg.generated
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qqNum
     *
     * @mbg.generated
     */
    private String qqnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weiChatNum
     *
     * @mbg.generated
     */
    private String weichatnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vipEndTime
     *
     * @mbg.generated
     */
    private Integer vipendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.timeCreated
     *
     * @mbg.generated
     */
    private Integer timecreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickName
     *
     * @return the value of user.nickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickName
     *
     * @param nickname the value for user.nickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vipLevel
     *
     * @return the value of user.vipLevel
     *
     * @mbg.generated
     */
    public Integer getViplevel() {
        return viplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.vipLevel
     *
     * @param viplevel the value for user.vipLevel
     *
     * @mbg.generated
     */
    public void setViplevel(Integer viplevel) {
        this.viplevel = viplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phoneNum
     *
     * @return the value of user.phoneNum
     *
     * @mbg.generated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phoneNum
     *
     * @param phonenum the value for user.phoneNum
     *
     * @mbg.generated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qqNum
     *
     * @return the value of user.qqNum
     *
     * @mbg.generated
     */
    public String getQqnum() {
        return qqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qqNum
     *
     * @param qqnum the value for user.qqNum
     *
     * @mbg.generated
     */
    public void setQqnum(String qqnum) {
        this.qqnum = qqnum == null ? null : qqnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weiChatNum
     *
     * @return the value of user.weiChatNum
     *
     * @mbg.generated
     */
    public String getWeichatnum() {
        return weichatnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weiChatNum
     *
     * @param weichatnum the value for user.weiChatNum
     *
     * @mbg.generated
     */
    public void setWeichatnum(String weichatnum) {
        this.weichatnum = weichatnum == null ? null : weichatnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vipEndTime
     *
     * @return the value of user.vipEndTime
     *
     * @mbg.generated
     */
    public Integer getVipendtime() {
        return vipendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.vipEndTime
     *
     * @param vipendtime the value for user.vipEndTime
     *
     * @mbg.generated
     */
    public void setVipendtime(Integer vipendtime) {
        this.vipendtime = vipendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.timeCreated
     *
     * @return the value of user.timeCreated
     *
     * @mbg.generated
     */
    public Integer getTimecreated() {
        return timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.timeCreated
     *
     * @param timecreated the value for user.timeCreated
     *
     * @mbg.generated
     */
    public void setTimecreated(Integer timecreated) {
        this.timecreated = timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gender=").append(gender);
        sb.append(", nickname=").append(nickname);
        sb.append(", viplevel=").append(viplevel);
        sb.append(", phonenum=").append(phonenum);
        sb.append(", qqnum=").append(qqnum);
        sb.append(", weichatnum=").append(weichatnum);
        sb.append(", vipendtime=").append(vipendtime);
        sb.append(", timecreated=").append(timecreated);
        sb.append(", avatar=").append(avatar);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}